### ISSUE TITLE
Use with Vite

### ISSUE THREAD

**Issue by bernardoadc** [robertknight/rollup-cache#11]
Not getting to work with Vite. Any ideas?
(Vite is compatible with rollup plugins, but yours didn't worked out of the box, nor in a similar way to your examples)

**Comment by robertknight** [comment]
> Not getting to work with Vite. Any ideas?

I'm not familiar with Vite. What version of Vite are you using and what exactly happens when you try to use it per this project's examples?

A Google search finds https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility with some notes that might be relevant. This plugin doesn't use the `moduleParsed` hook mentioned there and I believe the part about "If a Rollup plugin only makes sense for the build phase" is probably applicable.

**Comment by robertknight** [comment]
> So, reading that, it appears it could be done by:

Hmm, no, that won't work. `cacheBuild(...)` wraps the whole Rollup config. It is not a plugin for Rollup, as it needs to wrap other Rollup plugins. In a simple environment where you're just using Rollup, it would wrap the object that the Rollup config file exports. I don't know if this is possible with Vite.

**Comment by bernardoadc** [comment]
Ah, I see. Ok then, feel free to close the issue. Thanks Robert

**Comment by robertknight** [comment]
OK, I will do. If anyone else reading this figures out that it is possible to get this package working with Vite, let me know!
